### ISSUE TITLE
CSOMUnknownUser error on draft project

### ISSUE THREAD

**Issue by damirci** [OfficeDev/Project-Samples#1]
I'm using local Project Server 2013 and when I try to execute query on draft project I receive CSOMUnknownUser error.
line of code from this project that I'm getting that error are:

```
context.Load(draft.ProjectResources, dp => dp.Where(r => r.Name == localResourceName));       
context.ExecuteQuery();
```

I think I have a config problem in my Project Server

**Comment by superjijimouse** [comment]
Hi,
We guess maybe here are some setting/configuration issues. Could you please send us your ULSlogs after running the sample so that we could help you work around.

Thanks a lot,
Yue

**Comment by superjijimouse** [comment]
Hi,
We guess maybe here are some setting/configuration issues. Could you please send us your ULSlogs after running the sample so that we could help you work around.

Thanks a lot,
Yue

**Comment by damirci** [comment]
I tested Create-Update-Project-Samples and Uls Viewer logs are if flowing step by step:
`CreateProjectWithTaskAndAssignment()`:
>1. FollowedContent.RefreshFollowedItem(item.Url=http://developer2/PWA/New Project9, policy=Allow) : Local execution failed; Could not refresh followed item http://developer2/PWA/New Project9: Exception: Value cannot be null.  Parameter name: serviceContext

>2. Could not follow the url http://developer2/PWA/New Project9

>3. Standard Information:PSI Entry Point: <unknown>  Project User: <unknown>  Correlation Id: <unknown>  PWA Site URL:   SA Name: <unknown>  PSError: <unknown> A queue job has failed. This is a general error logged by the Project Server Queue everytime a job fails - for effective troubleshooting use this error message with other more specific error messages (if any), the Operations guide (which documents more details about queued jobs) and the trace log (which could provide more detailed context). More information about the failed job follows. GUID of the failed job: 712bd89d-fb0c-e611-8237-002522ade52c. Name of the computer that processed this job: 56ea5759-a1b0-400f-945c-dd6373b4daa2 (to debug further, you need to look at the trace log from this computer). Failed job type: ProjectUpdate. Failed sub-job type: ProjectUpdate2Message. Failed sub-job ID: 2. Stage where sub-job failed:  (this is useful when one sub-job has more than one logical processing stages).

`ReadAndUpdateProject()`:
I don't have error log is Uls Viewer but I have CSOMUnknownUser error.
