### ISSUE TITLE
Create Sub Projects

### ISSUE THREAD

**Issue by dgonzalezp** [OfficeDev/Project-Samples#2]
Hello, is there a way to create master projects and subprojects? Thank you very much!

**Comment by pirannia** [comment]
No. Master Projects and Subprojects creation and management are only supported by the Project Windows client.

**Comment by dgonzalezp** [comment]
Hello again, is there a way to change the resource Type from Work, (which is the default type) to Material type? All i can see is when I load the Task draft, I get the TaskType property but is read-only. Thank you in advance.

**Comment by pirannia** [comment]
No, once created the resource cannot change type using the API.
