### ISSUE TITLE
Home Page Links are wrong

### ISSUE THREAD

**Issue by kachihro** [OfficeDev/Project-Samples#22]
FYI - the doco is out of date - on this page ;
https://github.com/OfficeDev/Project-Samples/tree/master/O365-Project-Online-REST-Samples

Link should direct to HERE ...>
https://github.com/OfficeDev/Project-Samples/blob/master/O365-Project-Online-REST-Samples/createproject.ps1

Instead of ...>
https://github.com/OfficeDev/Project-Samples/blob/master/createproject.ps1

It's missing **[O365-Project-Online-REST-Samples]** in the url.

**Comment by lindalu-MSFT** [comment]
Fixed
