### ISSUE TITLE
Change the resourse Type from Work to Material

### ISSUE THREAD

**Issue by dgonzalezp** [OfficeDev/Project-Samples#3]
Hello again, is there a way to change the resource Type from Work type (which is the default type) to Material type?. Thank you in advance.

**Comment by superjijimouse** [comment]
Hi, 
Sorry for late reply. Changing resource Type is not supported in Project Server and type must be established at the resource creation time.

**Comment by dgonzalezp** [comment]
Hi! Thank you very much for your answer! Thats what I need, how do I establish the type at creaton time? At ProjectResourceCreationInformation I only have (Account, Email, Id, Name and Notes), there's also TypeId, but its read only. Thank you again in advance.

**Comment by dgonzalezp** [comment]
Hello again Yue, I'm trying to create set the resource type at the creation time, but I haven't found the way, do you have any example on how to do this? I'd really appreciate your help. Thank you in adavance

**Comment by pirannia** [comment]
https://msdn.microsoft.com/en-us/library/office/microsoft.projectserver.client.enterpriseresourcecreationinformation.resourcetype_di_pj14mref.aspx
